#Drone CI File!
#Commit Message: Drone! Captain Canary is here! 

# kind: pipeline
# type: kubernetes
# name: default

# steps:
   
# - name: build
#   image: centos:7
#   commands: 
#     - sleep 10
  
# - name: publish  
#   image: plugins/docker 
#   settings:
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     repo: amitsharma17133129/drone_test
#     auto_tag: true
#     auto_tag_suffix: drone-build
 
kind: pipeline
type: docker
name: test

steps:
- name: dist
  image: node
  commands:
  - npm install
  - npm run dist
